export const WORD_ARR = [
  {"french":"s'abonner à","english":"to subscribe to","wordType":"verb"},
  {"french":"s'adapter à","english":"to adapt to","wordType":"verb"},
  {"french":"s'adresser à","english":"to talk to someone","wordType":"verb"},
  {"french":"s'agenouiller","english":"to get on one's knees","wordType":"verb"},
  {"french":"s'allonger","english":"to lie down","wordType":"verb"},
  {"french":"s'appeler","english":"to be named","wordType":"verb"},
  {"french":"s'approcher de qq'un","english":"to get closer to someone","wordType":"verb"},
  {"french":"s'appuyer sur/contre/à","english":"to lean against","wordType":"verb"},
  {"french":"s'asseoir","english":"to sit down","wordType":"verb"},
  {"french":"s'attendre à","english":"to expect something","wordType":"verb"},
  {"french":"s'avancer","english":"to get closer","wordType":"verb"},
  {"french":"se baigner","english":"to bathe, swim","wordType":"verb"},
  {"french":"se baisser","english":"to lower oneself","wordType":"verb"},
  {"french":"se balader","english":"to take a stroll","wordType":"verb"},
  {"french":"se brosser (les cheveux, les dents…)","english":"to brush (one's hair, teeth…)","wordType":"verb"},
  {"french":"se brûler","english":"to burn oneself","wordType":"verb"},
  {"french":"se cacher","english":"to hide","wordType":"verb"},
  {"french":"se calmer","english":"to calm down","wordType":"verb"},
  {"french":"se changer","english":"to change outfit","wordType":"verb"},
  {"french":"se cogner (la tête)","english":"to bang one's head","wordType":"verb"},
  {"french":"se coincer","english":"to get stucked","wordType":"verb"},
  {"french":"se casser (la jambe)","english":"to break (one's leg)","wordType":"verb"},
  {"french":"se coiffer (les cheveux)","english":"to fix one's hair","wordType":"verb"},
  {"french":"se coucher","english":"to go to bed","wordType":"verb"},
  {"french":"se couper (le doigt)","english":"to cut oneself on the finger","wordType":"verb"},
  {"french":"se décider à","english":"to make the decision to","wordType":"verb"},
  {"french":"se défendre contre","english":"to defend against","wordType":"verb"},
  {"french":"se déguiser","english":"to put on a costume","wordType":"verb"},
  {"french":"se déshabiller","english":"to get undressed","wordType":"verb"},
  {"french":"se distraire","english":"to amuse oneself","wordType":"verb"},
  {"french":"se divertir","english":"to amuse oneself","wordType":"verb"},
  {"french":"se documenter","english":"to get documentation","wordType":"verb"},
  {"french":"se doucher","english":"to take a shower","wordType":"verb"},
  {"french":"s'effondrer","english":"to collapse","wordType":"verb"},
  {"french":"s'énerver","english":"to get angry","wordType":"verb"},
  {"french":"s'ennuyer","english":"to be bored","wordType":"verb"},
  {"french":"s'entraîner","english":"to train","wordType":"verb"},
  {"french":"s'enrhumer","english":"to be getting a cold","wordType":"verb"},
  {"french":"s'essuyer","english":"to dry oneself","wordType":"verb"},
  {"french":"s'étendre","english":"to lie down","wordType":"verb"},
  {"french":"s'évader","english":"to escape","wordType":"verb"},
  {"french":"s'évanouir","english":"to faint","wordType":"verb"},
  {"french":"s'excuser de","english":"to apologize","wordType":"verb"},
  {"french":"s'exercer","english":"to train","wordType":"verb"},
  {"french":"s'expliquer","english":"to explain oneself","wordType":"verb"},
  {"french":"se fâcher","english":"to get angry","wordType":"verb"},
  {"french":"se fatiguer","english":"to get tired","wordType":"verb"},
  {"french":"se fiancer","english":"to get engaged","wordType":"verb"},
  {"french":"se fouler (la cheville)","english":"to twist (one's ankle)","wordType":"verb"},
  {"french":"se fracturer (le bras)","english":"to break (one's arm)","wordType":"verb"},
  {"french":"se frotter","english":"to brush against","wordType":"verb"},
  {"french":"se garer","english":"to park","wordType":"verb"},
  {"french":"se gratter","english":"to scratch an itch","wordType":"verb"},
  {"french":"se goinfrer","english":"to eat like a pig","wordType":"verb"},
  {"french":"s'habiller","english":"to get dressed","wordType":"verb"},
  {"french":"s'habituer à","english":"to get accustomed to","wordType":"verb"},
  {"french":"s'impatienter","english":"to get impatient","wordType":"verb"},
  {"french":"s'infecter","english":"to get infected","wordType":"verb"},
  {"french":"s'intéresser à","english":"to be interested in","wordType":"verb"},
  {"french":"se lamenter","english":"to lament","wordType":"verb"},
  {"french":"se laver (les mains, la visage)","english":"to wash (one's hands, face…)","wordType":"verb"},
  {"french":"se lever","english":"to get up","wordType":"verb"},
  {"french":"se limiter à","english":"to limit oneself to","wordType":"verb"},
  {"french":"se marier (avec)","english":"to get married with someone","wordType":"verb"},
  {"french":"se maquiller","english":"to put on make-up","wordType":"verb"},
  {"french":"se mettre à fqqc","english":"to start doing something","wordType":"verb"},
  {"french":"se moquer de qqn","english":"to make fun of","wordType":"verb"},
  {"french":"se moucher","english":"to blow one's nose","wordType":"verb"},
  {"french":"se mouiller","english":"to get wet","wordType":"verb"},
  {"french":"se multiplier","english":"to multiply","wordType":"verb"},
  {"french":"se mutiner","english":"to declare mutiny","wordType":"verb"},
  {"french":"se négliger","english":"to neglect oneself","wordType":"verb"},
  {"french":"se nourrir","english":"to feed oneself","wordType":"verb"},
  {"french":"se noyer","english":"to drown","wordType":"verb"},
  {"french":"s'opposer à","english":"to oppose","wordType":"verb"},
  {"french":"s'organiser","english":"to get organized","wordType":"verb"},
  {"french":"se passionner pour","english":"to get passionate about","wordType":"verb"},
  {"french":"se pencher","english":"to lean down","wordType":"verb"},
  {"french":"se peigner (les cheveux)","english":"to comb one's hair","wordType":"verb"},
  {"french":"se pendre","english":"to hang oneself","wordType":"verb"},
  {"french":"se plaindre de","english":"to complain","wordType":"verb"},
  {"french":"se pousser","english":"to get out of the way","wordType":"verb"},
  {"french":"se précipiter","english":"to hurry towards","wordType":"verb"},
  {"french":"se préparer","english":"to get ready","wordType":"verb"},
  {"french":"se promener","english":"to take a stroll","wordType":"verb"},
  {"french":"se protéger de","english":"to protect oneself against","wordType":"verb"},
  {"french":"se qualifier","english":"to get qualified","wordType":"verb"},
  {"french":"se raser (la barbe)","english":"to shave","wordType":"verb"},
  {"french":"se rasseoir","english":"to go back to one's seat","wordType":"verb"},
  {"french":"se réchauffer","english":"to get warmer","wordType":"verb"},
  {"french":"se renseigner","english":"to get info","wordType":"verb"},
  {"french":"se reposer","english":"to rest","wordType":"verb"},
  {"french":"se retourner","english":"to turn around/back","wordType":"verb"},
  {"french":"se réveiller","english":"to wake up","wordType":"verb"},
  {"french":"se salir","english":"to get dirty","wordType":"verb"},
  {"french":"se sauver","english":"to escape","wordType":"verb"},
  {"french":"se séparer","english":"to separate from","wordType":"verb"},
  {"french":"se servir de","english":"to use","wordType":"verb"},
  {"french":"se suicider","english":"to commit suicide","wordType":"verb"},
  {"french":"se taire","english":"to be silent","wordType":"verb"},
  {"french":"se teindre (les cheveux)","english":"to color (one's hair)","wordType":"verb"},
  {"french":"se tourner vers","english":"to turn towards","wordType":"verb"},
  {"french":"se tromper","english":"to make a mistake","wordType":"verb"},
  {"french":"se tuer","english":"to kill oneself","wordType":"verb"},
  {"french":"se vanter","english":"to brag","wordType":"verb"},
  {"french":"se venger de","english":"to get revenge against","wordType":"verb"},
  {"french":"se vexer","english":"to get one's feeling hurt","wordType":"verb"},
  {"french":"aider à fqqc","english":"to help to do s.t","wordType":"verb"},
  {"french":"apprendre à fqqc","english":"to learn how to do s.t","wordType":"verb"},
  {"french":"arriver à fqqc","english":"to manage / succeed in doing s.t","wordType":"verb"},
  {"french":"avoir à fqqc","english":"to have to / be obliged to do s.t","wordType":"verb"},
  {"french":"chercher à fqqc","english":"to attempt to do s.t","wordType":"verb"},
  {"french":"commencer à fqqc","english":"to begin to do s.t","wordType":"verb"},
  {"french":"continuer à fqqc","english":"to continue to do s.t","wordType":"verb"},
  {"french":"consentir à fqqc","english":"to agree to do s.t","wordType":"verb"},
  {"french":"encourager qq'un à fqqc","english":"to encourage s.o to do s.t","wordType":"verb"},
  {"french":"hésiter à fqqc","english":"to hesitate to do s.t","wordType":"verb"},
  {"french":"inviter (qq'un) à fqqc","english":"to invite (s.o) to do s.t","wordType":"verb"},
  {"french":"obliger (qq'un) à fqqc","english":"to force (s.o) to do s.t","wordType":"verb"},
  {"french":"parvenir à fqqc","english":"to succeed in doing s.t","wordType":"verb"},
  {"french":"passer du temps à fqqc","english":"to spend time doing","wordType":"verb"},
  {"french":"perdre du temps à fqqc","english":"to waste time doing","wordType":"verb"},
  {"french":"persister à fqqc","english":"to persist in doing","wordType":"verb"},
  {"french":"pousser (qq'un) à fqqc","english":"to push s.o to do s.t","wordType":"verb"},
  {"french":"se préparer à fqqc","english":"to prepare oneself to do s.t","wordType":"verb"},
  {"french":"recommencer à fqqc","english":"to begin doing s.t again","wordType":"verb"},
  {"french":"renoncer à fqqc","english":"to give up doing s.t","wordType":"verb"},
  {"french":"résister à fqqc","english":"to resist doing","wordType":"verb"},
  {"french":"réussir à fqqc","english":"to succeed in doing","wordType":"verb"},
  {"french":"servir à fqqc","english":"to be used to do s.t","wordType":"verb"},
  {"french":"tenir à fqqc ","english":"to insist on doing s.t","wordType":"verb"},
  {"french":"s'amuser à fqqc","english":"to have fun doing s.t","wordType":"verb"},
  {"french":"s'autoriser à fqqc","english":"to allow oneself to do s.t","wordType":"verb"},
  {"french":"s'intéresser à qqc","english":"to show a special interest in s.t","wordType":"verb"},
  {"french":"acheter (qqc) à qq'un","english":"to buy s.t from or for s.o","wordType":"verb"},
  {"french":"arracher  à","english":"to tear away from s.o","wordType":"verb"},
  {"french":"conseiller   à qq'un","english":"to advise s.o","wordType":"verb"},
  {"french":"demander  à qq'un","english":"to ask (s.t) of s.o","wordType":"verb"},
  {"french":"défendre à qq'un","english":"to forbid s.o","wordType":"verb"},
  {"french":"désobéir à qq'un","english":"to disobey s.o","wordType":"verb"},
  {"french":"dire à qq'un","english":"to tell s.o","wordType":"verb"},
  {"french":"donner à qq'un","english":"to give (to) s.o","wordType":"verb"},
  {"french":"écrire à qq'un","english":"to write to s.o","wordType":"verb"},
  {"french":"emprunter à qq'un","english":"to borrow from s.o","wordType":"verb"},
  {"french":"envoyer à qq'un","english":"to send (to) s.o","wordType":"verb"},
  {"french":"être à","english":"to belong to s.o","wordType":"verb"},
  {"french":"faire attention à qq'un","english":"to pay attention to qq'un/ be careful with s.o","wordType":"verb"},
  {"french":"goûter à la confiture","english":"to taste the jam","wordType":"verb"},
  {"french":"interdire à qq'un","english":"to forbid s.o","wordType":"verb"},
  {"french":"jouer à","english":"to play (a game or sport)","wordType":"verb"},
  {"french":"obéir à qq'un","english":"to obey s.o","wordType":"verb"},
  {"french":"ordonner à qq'un","english":"to order s.o","wordType":"verb"},
  {"french":"pardonner à qq'un","english":"to forgive s.o","wordType":"verb"},
  {"french":"parler à qq'un","english":"to talk to s.o","wordType":"verb"},
  {"french":"penser à qq'un","english":"to think about s.o","wordType":"verb"},
  {"french":"permettre à qq'un","english":"to allow s.o","wordType":"verb"},
  {"french":"plaire à qq'un","english":"to please s.o","wordType":"verb"},
  {"french":"profiter à qq'un","english":"to benefit s.o","wordType":"verb"},
  {"french":"promettre à qq'un","english":"to promise s.o","wordType":"verb"},
  {"french":"réfléchir à","english":"to consider / reflect upon","wordType":"verb"},
  {"french":"répondre à qq'un","english":"to answer s.o","wordType":"verb"},
  {"french":"résister à qq'un","english":"to resist s.o","wordType":"verb"},
  {"french":"ressembler à qq'un","english":"to look like s.o","wordType":"verb"},
  {"french":"réussir à l'examen","english":"to pass the test","wordType":"verb"},
  {"french":"serrer la main à qq'un","english":"to shake hands with s.o","wordType":"verb"},
  {"french":"servir à qq'un","english":"to be useful for s.o","wordType":"verb"},
  {"french":"téléphoner à qq'un","english":"to call s.o","wordType":"verb"},
  {"french":"voler (qqc) à qq'un","english":"to steal (s.t) from s.o","wordType":"verb"},
  {"french":"accepter de fqqc","english":"to accept to do s.t","wordType":"verb"},
  {"french":"accuser (qq'un) de fqqc","english":"to accuse (s.o) of doing s.t","wordType":"verb"},
  {"french":"arrêter de fqqc","english":"to stop doing s.t","wordType":"verb"},
  {"french":"avoir peur de fqqc","english":"to be afraid of doing s.t","wordType":"verb"},
  {"french":"avoir envie de fqqc","english":"to feel like doing s.t","wordType":"verb"},
  {"french":"avoir besoin de fqqc","english":"to need to do s.t","wordType":"verb"},
  {"french":"avoir l'air de fqqc","english":"to seem to be doing s.t","wordType":"verb"},
  {"french":"avoir l'intention de fqqc","english":"to intend to do s.t","wordType":"verb"},
  {"french":"avoir raison de fqqc","english":"to be right to do s.t","wordType":"verb"},
  {"french":"avoir tort de fqqc","english":"to be wrong to do s.t","wordType":"verb"},
  {"french":"cesser de fqqc","english":"to cease doing s.t","wordType":"verb"},
  {"french":"choisir de fqqc","english":"to choose to do s.t","wordType":"verb"},
  {"french":"commander (à qqun) de fqqc","english":"to order (s.o) to do s.t","wordType":"verb"},
  {"french":"conseiller de fqqc","english":"to advise to do s.t","wordType":"verb"},
  {"french":"continuer de fqqc","english":"to keep doing s.t","wordType":"verb"},
  {"french":"craindre de fqqc","english":"  to fear doing s.t","wordType":"verb"},
  {"french":"décider de fqqc","english":"to decide to s.t","wordType":"verb"},
  {"french":"défendre (à qq'un) de fqqc","english":"to forbid (s.o) to do s.t","wordType":"verb"},
  {"french":"demander (à qq'un) de fqqc","english":"to ask (s.o) to do s.t","wordType":"verb"},
  {"french":"se dépêcher de fqqc","english":"to hurry to do s.t","wordType":"verb"},
  {"french":"dire (à qq'un) de fqqc","english":"to tell (s.o) to do s.t","wordType":"verb"},
  {"french":"empêcher (qq'un) de fqqc","english":"to keep (s.o) from doing s.t","wordType":"verb"},
  {"french":"essayer de fqqc","english":"to try to do s.t","wordType":"verb"},
  {"french":"finir de fqqc","english":"to finish doing s.t","wordType":"verb"},
  {"french":"manquer de fqqc","english":"to neglect doing s.t","wordType":"verb"},
  {"french":"mériter de fqqc","english":"to deserve to do s.t","wordType":"verb"},
  {"french":"offrir de fqqc","english":"to offer to do s.t","wordType":"verb"},
  {"french":"oublier de fqqc","english":"to forget to do s.t","wordType":"verb"},
  {"french":"parler de fqqc","english":"to talk about doing s.t","wordType":"verb"},
  {"french":"se permettre de fqqc","english":"to allow oneself to do s.t","wordType":"verb"},
  {"french":"promettre de fqqc","english":"to promise to do s.t","wordType":"verb"},
  {"french":"proposer de fqqc","english":"to suggest to do s.t","wordType":"verb"},
  {"french":"refuser de fqqc","english":"to refuse to do s.t","wordType":"verb"},
  {"french":"regretter de fqqc","english":"to regret doing s.t","wordType":"verb"},
  {"french":"remercier de fqqc","english":"to thank for doing s.t","wordType":"verb"},
  {"french":"rêver de fqqc","english":"to dream of doing s.t","wordType":"verb"},
  {"french":"risquer de fqqc","english":"to risk doing s.t","wordType":"verb"},
  {"french":"se souvenir de fqqc","english":"to remember doing s.t","wordType":"verb"},
  {"french":"supplier de fqqc","english":"to beg to do s.t","wordType":"verb"},
  {"french":"venir de fqqc","english":"to have just done s.t","wordType":"verb"},
  {"french":"se contenter de fqqc","english":"to content oneself with doing s.t","wordType":"verb"},
  {"french":"convaincre (qq'un) de fqqc","english":"to convince (s.o) to do s.t","wordType":"verb"},
  {"french":"s'efforcer de fqqc","english":"to try hard to do s.t","wordType":"verb"},
  {"french":"empêcher (qq'un) de fqqc","english":"to prevent s.o from doing s.t","wordType":"verb"},
  {"french":"envisager de fqqc","english":"to contemplate doing s.t","wordType":"verb"},
  {"french":"éviter de fqqc","english":"to avoid doing s.t","wordType":"verb"},
  {"french":"faire semblant de fqqc","english":"to pretend doing s.t","wordType":"verb"},
  {"french":"feindre de fqqc","english":"to feign to, to pretend doing s.t","wordType":"verb"},
  {"french":"interdire (à qq'un) de fqqc","english":"to forbid (s.o) to do s.t","wordType":"verb"},
  {"french":"menacer (qq'un) de fqqc","english":"to threaten (s.o) to do s.t","wordType":"verb"},
  {"french":"persuader (qq'un) de fqqc","english":"to convince (s.o) to do s.t","wordType":"verb"},
  {"french":"projeter de fqqc","english":"to plan on doing s.t","wordType":"verb"},
  {"french":"reprocher (à qq'un) de fqqc","english":"to reproach (s.o) for doing s.t","wordType":"verb"},
  {"french":"soupçonner (qq'un) de fqqc","english":"to suspect (s.o) of doing s.t","wordType":"verb"},
  {"french":"tâcher de fqqc","english":"to try to do s.t","wordType":"verb"},
  {"french":"s'apercevoir de son erreur","english":"to notice one's mistake","wordType":"verb"},
  {"french":"changer de chaussure","english":"to change into other shoes","wordType":"verb"},
  {"french":"dépendre de qq'un","english":"to depend on s.o","wordType":"verb"},
  {"french":"douter de qq'un","english":"to doubt s.o","wordType":"verb"},
  {"french":"être responsable de qq'un","english":"to be responsible for s.o","wordType":"verb"},
  {"french":"hériter de qq'un","english":"to inherit from s.o","wordType":"verb"},
  {"french":"manquer de temps","english":"to lack time","wordType":"verb"},
  {"french":"se méfier de qq'un","english":"to beware of s.o","wordType":"verb"},
  {"french":"s'occuper de qq'un","english":"to take care of s.o","wordType":"verb"},
  {"french":"parler de qq'un","english":"to talk about s.o","wordType":"verb"},
  {"french":"partir de France","english":"to leave France","wordType":"verb"},
  {"french":"se passer de qq'un","english":"to do without s.o","wordType":"verb"},
  {"french":"Que penses-tu de qq'un?","english":"what is your opinion about s.o?","wordType":"verb"},
  {"french":"profiter de qq'un","english":"to take advantage of s.o","wordType":"verb"},
  {"french":"rêver de qq'un","english":"to dream of s.o","wordType":"verb"},
  {"french":"rire de qq'un","english":"to laugh at s.o","wordType":"verb"},
  {"french":"se souvenir de qq'un","english":"to remember s.o","wordType":"verb"}
];
