module.exports = WORD_ARR = [
{ "english": "to be :arrows_counterclockwise:", "french": "ser", "wordType": "noun" },
{ "english": "I am :arrows_counterclockwise:", "french": "yo soy", "wordType": "noun" },
{ "english": "you are :arrows_counterclockwise: :smiley:", "french": "tú eres", "wordType": "noun" },
{ "english": "he is :arrows_counterclockwise:", "french": "el es", "wordType": "noun" },
{ "english": "she is :arrows_counterclockwise:", "french": "ella es", "wordType": "noun" },
{ "english": "you are :arrows_counterclockwise: 👤", "french": "usted es", "wordType": "noun" },
{ "english": "we are :arrows_counterclockwise:", "french": "nosotros somos", "wordType": "noun" },
{ "english": "you are :arrows_counterclockwise: :smiley::smiley::smiley:", "french": "vosotros sois", "wordType": "noun" },
{ "english": "they are :arrows_counterclockwise: :man:", "french": "ellos son", "wordType": "noun" },
{ "english": "they are :arrows_counterclockwise: :woman:", "french": "ellas son", "wordType": "noun" },
{ "english": "you are :arrows_counterclockwise: 👤👤👤", "french": "ustedes son", "wordType": "noun" },
{ "english": "to be :clock1:", "french": "estar", "wordType": "noun" },
{ "english": "I am :clock1:", "french": "yo estoy", "wordType": "noun" },
{ "english": "you are :clock1::smiley:", "french": "tú estás", "wordType": "noun" },
{ "english": "he is :clock1:", "french": "el está", "wordType": "noun" },
{ "english": "she is :clock1:", "french": "ella está", "wordType": "noun" },
{ "english": "you are :clock1: 👤", "french": "usted está", "wordType": "noun" },
{ "english": "we are :clock1:", "french": "nosotros estamos", "wordType": "noun" },
{ "english": "you are :clock1::smiley::smiley::smiley:", "french": "vosotros estáis", "wordType": "noun" },
{ "english": "they are :clock1:♂️", "french": "ellos están", "wordType": "noun" },
{ "english": "they are :clock1::woman:", "french": "ellas están", "wordType": "noun" },
{ "english": "you are :clock1: 👤👤👤", "french": "ustedes están", "wordType": "noun" },
{ "english": "to go", "french": "ir", "wordType": "noun" },
{ "english": "I go", "french": "yo voy", "wordType": "noun" },
{ "english": "you go :smiley:", "french": "tú vas", "wordType": "noun" },
{ "english": "he goes", "french": "el va", "wordType": "noun" },
{ "english": "she goes", "french": "ella va", "wordType": "noun" },
{ "english": "you go 👤", "french": "usted va", "wordType": "noun" },
{ "english": "we go", "french": "nosotros vamos", "wordType": "noun" },
{ "english": "you go :smiley::smiley::smiley:", "french": "vosotros vais", "wordType": "noun" },
{ "english": "they go :man:", "french": "ellos van", "wordType": "noun" },
{ "english": "they go :woman:", "french": "ellas van", "wordType": "noun" },
{ "english": "you go 👤👤👤", "french": "ustedes van", "wordType": "noun" },
{ "english": "to want", "french": "querer", "wordType": "noun" },
{ "english": "I want", "french": "yo quiero", "wordType": "noun" },
{ "english": "you want :smiley:", "french": "tú quieres", "wordType": "noun" },
{ "english": "he wants", "french": "el quiere", "wordType": "noun" },
{ "english": "she wants", "french": "ella quiere", "wordType": "noun" },
{ "english": "you want 👤", "french": "usted quiere", "wordType": "noun" },
{ "english": "we want", "french": "nosotros queremos", "wordType": "noun" },
{ "english": "you want :smiley::smiley::smiley:", "french": "vosotros queréis", "wordType": "noun" },
{ "english": "they want :man:", "french": "ellos quieren", "wordType": "noun" },
{ "english": "they want :woman:", "french": "ellas quieren", "wordType": "noun" },
{ "english": "you want 👤👤👤", "french": "ustedes quieren", "wordType": "noun" },
{ "english": "Can / be able", "french": "poder", "wordType": "noun" },
{ "english": "I can / am able", "french": "yo puedo", "wordType": "noun" },
{ "english": "you can / are able :smiley:", "french": "tú puedes", "wordType": "noun" },
{ "english": "he can / is able", "french": "el puede", "wordType": "noun" },
{ "english": "she can / is able", "french": "ella puede", "wordType": "noun" },
{ "english": "you can / are able 👤", "french": "usted puede", "wordType": "noun" },
{ "english": "we can / are able", "french": "nosotros podemos", "wordType": "noun" },
{ "english": "you can / are able :smiley::smiley::smiley:", "french": "vosotros podéis", "wordType": "noun" },
{ "english": "they can / are able :man:", "french": "ellos pueden", "wordType": "noun" },
{ "english": "they can / are able :woman:", "french": "ellas pueden", "wordType": "noun" },
{ "english": "you can / are able 👤👤👤", "french": "ustedes pueden", "wordType": "noun" },
{ "english": "to do / make", "french": "hacer", "wordType": "noun" },
{ "english": "I do / make", "french": "yo hago", "wordType": "noun" },
{ "english": "you do / make :smiley:", "french": "tú haces", "wordType": "noun" },
{ "english": "he makes / does", "french": "el hace", "wordType": "noun" },
{ "english": "she makes / does", "french": "ella hace", "wordType": "noun" },
{ "english": "you do / make 👤", "french": "usted hace", "wordType": "noun" },
{ "english": "we do / make", "french": "nosotros hacemos", "wordType": "noun" },
{ "english": "you do / make :smiley::smiley::smiley:", "french": "vosotros hacéis", "wordType": "noun" },
{ "english": "they do / make :man:", "french": "ellos hacen", "wordType": "noun" },
{ "english": "they do / make :woman:", "french": "ellas hacen", "wordType": "noun" },
{ "english": "you do / make 👤👤👤", "french": "ustedes hacen", "wordType": "noun" },
{ "english": "to know", "french": "saber", "wordType": "noun" },
{ "english": "I know", "french": "yo sé", "wordType": "noun" },
{ "english": "you know :smiley:", "french": "tú sabes", "wordType": "noun" },
{ "english": "he knows", "french": "el sabe", "wordType": "noun" },
{ "english": "she knows", "french": "ella sabe", "wordType": "noun" },
{ "english": "you know 👤", "french": "usted sabe", "wordType": "noun" },
{ "english": "we know", "french": "nosotros sabemos", "wordType": "noun" },
{ "english": "you know :smiley::smiley::smiley:", "french": "vosotros sabéis", "wordType": "noun" },
{ "english": "they know :man:", "french": "ellos saben", "wordType": "noun" },
{ "english": "they know :woman:", "french": "ellas saben", "wordType": "noun" },
{ "english": "you know 👤👤👤", "french": "ustedes saben", "wordType": "noun" },
{ "english": "to give", "french": "dar", "wordType": "noun" },
{ "english": "I give", "french": "yo doy", "wordType": "noun" },
{ "english": "you give :smiley:", "french": "tú das", "wordType": "noun" },
{ "english": "he gives", "french": "el da", "wordType": "noun" },
{ "english": "she gives", "french": "ella da", "wordType": "noun" },
{ "english": "you give 👤", "french": "usted da", "wordType": "noun" },
{ "english": "we give", "french": "nosotros damos", "wordType": "noun" },
{ "english": "you give :smiley::smiley::smiley:", "french": "vosotros dais", "wordType": "noun" },
{ "english": "they give :man:", "french": "ellos dan", "wordType": "noun" },
{ "english": "they give :woman:", "french": "ellas dan", "wordType": "noun" },
{ "english": "you give 👤👤👤", "french": "ustedes dan", "wordType": "noun" },
{ "english": "to have", "french": "tener", "wordType": "noun" },
{ "english": "I have", "french": "yo tengo", "wordType": "noun" },
{ "english": "you have :smiley:", "french": "tú tienes", "wordType": "noun" },
{ "english": "he has", "french": "el tiene", "wordType": "noun" },
{ "english": "she has", "french": "ella tiene", "wordType": "noun" },
{ "english": "you have 👤", "french": "usted tiene", "wordType": "noun" },
{ "english": "we have", "french": "nosotros tenemos", "wordType": "noun" },
{ "english": "you have :smiley::smiley::smiley:", "french": "vosotros tenéis", "wordType": "noun" },
{ "english": "they have :man:", "french": "ellos tienen", "wordType": "noun" },
{ "english": "they have :woman:", "french": "ellas tienen", "wordType": "noun" },
{ "english": "you have 👤👤👤", "french": "ustedes tienen", "wordType": "noun" },
{ "english": "to come", "french": "venir", "wordType": "noun" },
{ "english": "I come", "french": "yo vengo", "wordType": "noun" },
{ "english": "you comes :smiley:", "french": "tú vienes", "wordType": "noun" },
{ "english": "he comes", "french": "el viene", "wordType": "noun" },
{ "english": "she come", "french": "ella viene", "wordType": "noun" },
{ "english": "you come 👤", "french": "usted viene", "wordType": "noun" },
{ "english": "we come", "french": "nosotros venimos", "wordType": "noun" },
{ "english": "you come :smiley::smiley::smiley:", "french": "vosotros venís", "wordType": "noun" },
{ "english": "they come :man:", "french": "ellos vienen", "wordType": "noun" },
{ "english": "they come :woman:", "french": "ellas vienen", "wordType": "noun" },
{ "english": "you come 👤👤👤", "french": "ustedes vienen", "wordType": "noun" },
{ "english": "to think", "french": "pensar", "wordType": "noun" },
{ "english": "I think", "french": "yo pienso", "wordType": "noun" },
{ "english": "you think :smiley:", "french": "tú piensas", "wordType": "noun" },
{ "english": "he thinks", "french": "el piensa", "wordType": "noun" },
{ "english": "she thinks", "french": "ella piensa", "wordType": "noun" },
{ "english": "you think 👤", "french": "usted piensa", "wordType": "noun" },
{ "english": "we think", "french": "nosotros pensamos", "wordType": "noun" },
{ "english": "you think :smiley::smiley::smiley:", "french": "vosotros pensáis", "wordType": "noun" },
{ "english": "they think :man:", "french": "ellos piensan", "wordType": "noun" },
{ "english": "they think :woman:", "french": "ellas piensan", "wordType": "noun" },
{ "english": "you think 👤👤👤", "french": "ustedes piensan", "wordType": "noun" }];

// module.exports = WORD_ARR = [
// {"french":"s'abonner à","english":"to subscribe to","wordType":"verb"},
// {"french":"s'adapter à","english":"to adapt to","wordType":"verb"},
// {"french":"s'adresser à","english":"to talk to someone","wordType":"verb"},
// {"french":"s'agenouiller","english":"to get on one's knees","wordType":"verb"},
// {"french":"s'allonger","english":"to lie down","wordType":"verb"},
// {"french":"s'appeler","english":"to be named","wordType":"verb"},
// {"french":"s'approcher de qq'un","english":"to get closer to someone","wordType":"verb"},
// {"french":"s'appuyer sur/contre/à","english":"to lean against","wordType":"verb"},
// {"french":"s'asseoir","english":"to sit down","wordType":"verb"},
// {"french":"s'attendre à","english":"to expect something","wordType":"verb"},
// {"french":"s'avancer","english":"to get closer","wordType":"verb"},
// {"french":"se baigner","english":"to bathe, swim","wordType":"verb"},
// {"french":"se baisser","english":"to lower oneself","wordType":"verb"},
// {"french":"se balader","english":"to take a stroll","wordType":"verb"},
// {"french":"se brosser (les cheveux, les dents…)","english":"to brush (one's hair, teeth…)","wordType":"verb"},
// {"french":"se brûler","english":"to burn oneself","wordType":"verb"},
// {"french":"se cacher","english":"to hide","wordType":"verb"},
// {"french":"se calmer","english":"to calm down","wordType":"verb"},
// {"french":"se changer","english":"to change outfit","wordType":"verb"},
// {"french":"se cogner (la tête)","english":"to bang one's head","wordType":"verb"},
// {"french":"se coincer","english":"to get stucked","wordType":"verb"},
// {"french":"se casser (la jambe)","english":"to break (one's leg)","wordType":"verb"},
// {"french":"se coiffer (les cheveux)","english":"to fix one's hair","wordType":"verb"},
// {"french":"se coucher","english":"to go to bed","wordType":"verb"},
// {"french":"se couper (le doigt)","english":"to cut oneself on the finger","wordType":"verb"},
// {"french":"se décider à","english":"to make the decision to","wordType":"verb"},
// {"french":"se défendre contre","english":"to defend against","wordType":"verb"},
// {"french":"se déguiser","english":"to put on a costume","wordType":"verb"},
// {"french":"se déshabiller","english":"to get undressed","wordType":"verb"},
// {"french":"se distraire","english":"to amuse oneself","wordType":"verb"},
// {"french":"se divertir","english":"to amuse oneself","wordType":"verb"},
// {"french":"se documenter","english":"to get documentation","wordType":"verb"},
// {"french":"se doucher","english":"to take a shower","wordType":"verb"},
// {"french":"s'effondrer","english":"to collapse","wordType":"verb"},
// {"french":"s'énerver","english":"to get angry","wordType":"verb"},
// {"french":"s'ennuyer","english":"to be bored","wordType":"verb"},
// {"french":"s'entraîner","english":"to train","wordType":"verb"},
// {"french":"s'enrhumer","english":"to be getting a cold","wordType":"verb"},
// {"french":"s'essuyer","english":"to dry oneself","wordType":"verb"},
// {"french":"s'étendre","english":"to lie down","wordType":"verb"},
// {"french":"s'évader","english":"to escape","wordType":"verb"},
// {"french":"s'évanouir","english":"to faint","wordType":"verb"},
// {"french":"s'excuser de","english":"to apologize","wordType":"verb"},
// {"french":"s'exercer","english":"to train","wordType":"verb"},
// {"french":"s'expliquer","english":"to explain oneself","wordType":"verb"},
// {"french":"se fâcher","english":"to get angry","wordType":"verb"},
// {"french":"se fatiguer","english":"to get tired","wordType":"verb"},
// {"french":"se fiancer","english":"to get engaged","wordType":"verb"},
// {"french":"se fouler (la cheville)","english":"to twist (one's ankle)","wordType":"verb"},
// {"french":"se fracturer (le bras)","english":"to break (one's arm)","wordType":"verb"},
// {"french":"se frotter","english":"to brush against","wordType":"verb"},
// {"french":"se garer","english":"to park","wordType":"verb"},
// {"french":"se gratter","english":"to scratch an itch","wordType":"verb"},
// {"french":"se goinfrer","english":"to eat like a pig","wordType":"verb"},
// {"french":"s'habiller","english":"to get dressed","wordType":"verb"},
// {"french":"s'habituer à","english":"to get accustomed to","wordType":"verb"},
// {"french":"s'impatienter","english":"to get impatient","wordType":"verb"},
// {"french":"s'infecter","english":"to get infected","wordType":"verb"},
// {"french":"s'intéresser à","english":"to be interested in","wordType":"verb"},
// {"french":"se lamenter","english":"to lament","wordType":"verb"},
// {"french":"se laver (les mains, la visage)","english":"to wash (one's hands, face…)","wordType":"verb"},
// {"french":"se lever","english":"to get up","wordType":"verb"},
// {"french":"se limiter à","english":"to limit oneself to","wordType":"verb"},
// {"french":"se marier (avec)","english":"to get married with someone","wordType":"verb"},
// {"french":"se maquiller","english":"to put on make-up","wordType":"verb"},
// {"french":"se mettre à fqqc","english":"to start doing something","wordType":"verb"},
// {"french":"se moquer de qqn","english":"to make fun of","wordType":"verb"},
// {"french":"se moucher","english":"to blow one's nose","wordType":"verb"},
// {"french":"se mouiller","english":"to get wet","wordType":"verb"},
// {"french":"se multiplier","english":"to multiply","wordType":"verb"},
// {"french":"se mutiner","english":"to declare mutiny","wordType":"verb"},
// {"french":"se négliger","english":"to neglect oneself","wordType":"verb"},
// {"french":"se nourrir","english":"to feed oneself","wordType":"verb"},
// {"french":"se noyer","english":"to drown","wordType":"verb"},
// {"french":"s'opposer à","english":"to oppose","wordType":"verb"},
// {"french":"s'organiser","english":"to get organized","wordType":"verb"},
// {"french":"se passionner pour","english":"to get passionate about","wordType":"verb"},
// {"french":"se pencher","english":"to lean down","wordType":"verb"},
// {"french":"se peigner (les cheveux)","english":"to comb one's hair","wordType":"verb"},
// {"french":"se pendre","english":"to hang oneself","wordType":"verb"},
// {"french":"se plaindre de","english":"to complain","wordType":"verb"},
// {"french":"se pousser","english":"to get out of the way","wordType":"verb"},
// {"french":"se précipiter","english":"to hurry towards","wordType":"verb"},
// {"french":"se préparer","english":"to get ready","wordType":"verb"},
// {"french":"se promener","english":"to take a stroll","wordType":"verb"},
// {"french":"se protéger de","english":"to protect oneself against","wordType":"verb"},
// {"french":"se qualifier","english":"to get qualified","wordType":"verb"},
// {"french":"se raser (la barbe)","english":"to shave","wordType":"verb"},
// {"french":"se rasseoir","english":"to go back to one's seat","wordType":"verb"},
// {"french":"se réchauffer","english":"to get warmer","wordType":"verb"},
// {"french":"se renseigner","english":"to get info","wordType":"verb"},
// {"french":"se reposer","english":"to rest","wordType":"verb"},
// {"french":"se retourner","english":"to turn around/back","wordType":"verb"},
// {"french":"se réveiller","english":"to wake up","wordType":"verb"},
// {"french":"se salir","english":"to get dirty","wordType":"verb"},
// {"french":"se sauver","english":"to escape","wordType":"verb"},
// {"french":"se séparer","english":"to separate from","wordType":"verb"},
// {"french":"se servir de","english":"to use","wordType":"verb"},
// {"french":"se suicider","english":"to commit suicide","wordType":"verb"},
// {"french":"se taire","english":"to be silent","wordType":"verb"},
// {"french":"se teindre (les cheveux)","english":"to color (one's hair)","wordType":"verb"},
// {"french":"se tourner vers","english":"to turn towards","wordType":"verb"},
// {"french":"se tromper","english":"to make a mistake","wordType":"verb"},
// {"french":"se tuer","english":"to kill oneself","wordType":"verb"},
// {"french":"se vanter","english":"to brag","wordType":"verb"},
// {"french":"se venger de","english":"to get revenge against","wordType":"verb"},
// {"french":"se vexer","english":"to get one's feeling hurt","wordType":"verb"},
// {"french":"aider à fqqc","english":"to help to do s.t","wordType":"verb"},
// {"french":"apprendre à fqqc","english":"to learn how to do s.t","wordType":"verb"},
// {"french":"arriver à fqqc","english":"to manage / succeed in doing s.t","wordType":"verb"},
// {"french":"avoir à fqqc","english":"to have to / be obliged to do s.t","wordType":"verb"},
// {"french":"chercher à fqqc","english":"to attempt to do s.t","wordType":"verb"},
// {"french":"commencer à fqqc","english":"to begin to do s.t","wordType":"verb"},
// {"french":"continuer à fqqc","english":"to continue to do s.t","wordType":"verb"},
// {"french":"consentir à fqqc","english":"to agree to do s.t","wordType":"verb"},
// {"french":"encourager qq'un à fqqc","english":"to encourage s.o to do s.t","wordType":"verb"},
// {"french":"hésiter à fqqc","english":"to hesitate to do s.t","wordType":"verb"},
// {"french":"inviter (qq'un) à fqqc","english":"to invite (s.o) to do s.t","wordType":"verb"},
// {"french":"obliger (qq'un) à fqqc","english":"to force (s.o) to do s.t","wordType":"verb"},
// {"french":"parvenir à fqqc","english":"to succeed in doing s.t","wordType":"verb"},
// {"french":"passer du temps à fqqc","english":"to spend time doing","wordType":"verb"},
// {"french":"perdre du temps à fqqc","english":"to waste time doing","wordType":"verb"},
// {"french":"persister à fqqc","english":"to persist in doing","wordType":"verb"},
// {"french":"pousser (qq'un) à fqqc","english":"to push s.o to do s.t","wordType":"verb"},
// {"french":"se préparer à fqqc","english":"to prepare oneself to do s.t","wordType":"verb"},
// {"french":"recommencer à fqqc","english":"to begin doing s.t again","wordType":"verb"},
// {"french":"renoncer à fqqc","english":"to give up doing s.t","wordType":"verb"},
// {"french":"résister à fqqc","english":"to resist doing","wordType":"verb"},
// {"french":"réussir à fqqc","english":"to succeed in doing","wordType":"verb"},
// {"french":"servir à fqqc","english":"to be used to do s.t","wordType":"verb"},
// {"french":"tenir à fqqc ","english":"to insist on doing s.t","wordType":"verb"},
// {"french":"s'amuser à fqqc","english":"to have fun doing s.t","wordType":"verb"},
// {"french":"s'autoriser à fqqc","english":"to allow oneself to do s.t","wordType":"verb"},
// {"french":"s'intéresser à qqc","english":"to show a special interest in s.t","wordType":"verb"},
// {"french":"acheter (qqc) à qq'un","english":"to buy s.t from or for s.o","wordType":"verb"},
// {"french":"arracher  à","english":"to tear away from s.o","wordType":"verb"},
// {"french":"conseiller   à qq'un","english":"to advise s.o","wordType":"verb"},
// {"french":"demander  à qq'un","english":"to ask (s.t) of s.o","wordType":"verb"},
// {"french":"défendre à qq'un","english":"to forbid s.o","wordType":"verb"},
// {"french":"désobéir à qq'un","english":"to disobey s.o","wordType":"verb"},
// {"french":"dire à qq'un","english":"to tell s.o","wordType":"verb"},
// {"french":"donner à qq'un","english":"to give (to) s.o","wordType":"verb"},
// {"french":"écrire à qq'un","english":"to write to s.o","wordType":"verb"},
// {"french":"emprunter à qq'un","english":"to borrow from s.o","wordType":"verb"},
// {"french":"envoyer à qq'un","english":"to send (to) s.o","wordType":"verb"},
// {"french":"être à","english":"to belong to s.o","wordType":"verb"},
// {"french":"faire attention à qq'un","english":"to pay attention to qq'un/ be careful with s.o","wordType":"verb"},
// {"french":"goûter à la confiture","english":"to taste the jam","wordType":"verb"},
// {"french":"interdire à qq'un","english":"to forbid s.o","wordType":"verb"},
// {"french":"jouer à","english":"to play (a game or sport)","wordType":"verb"},
// {"french":"obéir à qq'un","english":"to obey s.o","wordType":"verb"},
// {"french":"ordonner à qq'un","english":"to order s.o","wordType":"verb"},
// {"french":"pardonner à qq'un","english":"to forgive s.o","wordType":"verb"},
// {"french":"parler à qq'un","english":"to talk to s.o","wordType":"verb"},
// {"french":"penser à qq'un","english":"to think about s.o","wordType":"verb"},
// {"french":"permettre à qq'un","english":"to allow s.o","wordType":"verb"},
// {"french":"plaire à qq'un","english":"to please s.o","wordType":"verb"},
// {"french":"profiter à qq'un","english":"to benefit s.o","wordType":"verb"},
// {"french":"promettre à qq'un","english":"to promise s.o","wordType":"verb"},
// {"french":"réfléchir à","english":"to consider / reflect upon","wordType":"verb"},
// {"french":"répondre à qq'un","english":"to answer s.o","wordType":"verb"},
// {"french":"résister à qq'un","english":"to resist s.o","wordType":"verb"},
// {"french":"ressembler à qq'un","english":"to look like s.o","wordType":"verb"},
// {"french":"réussir à l'examen","english":"to pass the test","wordType":"verb"},
// {"french":"serrer la main à qq'un","english":"to shake hands with s.o","wordType":"verb"},
// {"french":"servir à qq'un","english":"to be useful for s.o","wordType":"verb"},
// {"french":"téléphoner à qq'un","english":"to call s.o","wordType":"verb"},
// {"french":"voler (qqc) à qq'un","english":"to steal (s.t) from s.o","wordType":"verb"},
// {"french":"accepter de fqqc","english":"to accept to do s.t","wordType":"verb"},
// {"french":"accuser (qq'un) de fqqc","english":"to accuse (s.o) of doing s.t","wordType":"verb"},
// {"french":"arrêter de fqqc","english":"to stop doing s.t","wordType":"verb"},
// {"french":"avoir peur de fqqc","english":"to be afraid of doing s.t","wordType":"verb"},
// {"french":"avoir envie de fqqc","english":"to feel like doing s.t","wordType":"verb"},
// {"french":"avoir besoin de fqqc","english":"to need to do s.t","wordType":"verb"},
// {"french":"avoir l'air de fqqc","english":"to seem to be doing s.t","wordType":"verb"},
// {"french":"avoir l'intention de fqqc","english":"to intend to do s.t","wordType":"verb"},
// {"french":"avoir raison de fqqc","english":"to be right to do s.t","wordType":"verb"},
// {"french":"avoir tort de fqqc","english":"to be wrong to do s.t","wordType":"verb"},
// {"french":"cesser de fqqc","english":"to cease doing s.t","wordType":"verb"},
// {"french":"choisir de fqqc","english":"to choose to do s.t","wordType":"verb"},
// {"french":"commander (à qqun) de fqqc","english":"to order (s.o) to do s.t","wordType":"verb"},
// {"french":"conseiller de fqqc","english":"to advise to do s.t","wordType":"verb"},
// {"french":"continuer de fqqc","english":"to keep doing s.t","wordType":"verb"},
// {"french":"craindre de fqqc","english":"  to fear doing s.t","wordType":"verb"},
// {"french":"décider de fqqc","english":"to decide to s.t","wordType":"verb"},
// {"french":"défendre (à qq'un) de fqqc","english":"to forbid (s.o) to do s.t","wordType":"verb"},
// {"french":"demander (à qq'un) de fqqc","english":"to ask (s.o) to do s.t","wordType":"verb"},
// {"french":"se dépêcher de fqqc","english":"to hurry to do s.t","wordType":"verb"},
// {"french":"dire (à qq'un) de fqqc","english":"to tell (s.o) to do s.t","wordType":"verb"},
// {"french":"empêcher (qq'un) de fqqc","english":"to keep (s.o) from doing s.t","wordType":"verb"},
// {"french":"essayer de fqqc","english":"to try to do s.t","wordType":"verb"},
// {"french":"finir de fqqc","english":"to finish doing s.t","wordType":"verb"},
// {"french":"manquer de fqqc","english":"to neglect doing s.t","wordType":"verb"},
// {"french":"mériter de fqqc","english":"to deserve to do s.t","wordType":"verb"},
// {"french":"offrir de fqqc","english":"to offer to do s.t","wordType":"verb"},
// {"french":"oublier de fqqc","english":"to forget to do s.t","wordType":"verb"},
// {"french":"parler de fqqc","english":"to talk about doing s.t","wordType":"verb"},
// {"french":"se permettre de fqqc","english":"to allow oneself to do s.t","wordType":"verb"},
// {"french":"promettre de fqqc","english":"to promise to do s.t","wordType":"verb"},
// {"french":"proposer de fqqc","english":"to suggest to do s.t","wordType":"verb"},
// {"french":"refuser de fqqc","english":"to refuse to do s.t","wordType":"verb"},
// {"french":"regretter de fqqc","english":"to regret doing s.t","wordType":"verb"},
// {"french":"remercier de fqqc","english":"to thank for doing s.t","wordType":"verb"},
// {"french":"rêver de fqqc","english":"to dream of doing s.t","wordType":"verb"},
// {"french":"risquer de fqqc","english":"to risk doing s.t","wordType":"verb"},
// {"french":"se souvenir de fqqc","english":"to remember doing s.t","wordType":"verb"},
// {"french":"supplier de fqqc","english":"to beg to do s.t","wordType":"verb"},
// {"french":"venir de fqqc","english":"to have just done s.t","wordType":"verb"},
// {"french":"se contenter de fqqc","english":"to content oneself with doing s.t","wordType":"verb"},
// {"french":"convaincre (qq'un) de fqqc","english":"to convince (s.o) to do s.t","wordType":"verb"},
// {"french":"s'efforcer de fqqc","english":"to try hard to do s.t","wordType":"verb"},
// {"french":"empêcher (qq'un) de fqqc","english":"to prevent s.o from doing s.t","wordType":"verb"},
// {"french":"envisager de fqqc","english":"to contemplate doing s.t","wordType":"verb"},
// {"french":"éviter de fqqc","english":"to avoid doing s.t","wordType":"verb"},
// {"french":"faire semblant de fqqc","english":"to pretend doing s.t","wordType":"verb"},
// {"french":"feindre de fqqc","english":"to feign to, to pretend doing s.t","wordType":"verb"},
// {"french":"interdire (à qq'un) de fqqc","english":"to forbid (s.o) to do s.t","wordType":"verb"},
// {"french":"menacer (qq'un) de fqqc","english":"to threaten (s.o) to do s.t","wordType":"verb"},
// {"french":"persuader (qq'un) de fqqc","english":"to convince (s.o) to do s.t","wordType":"verb"},
// {"french":"projeter de fqqc","english":"to plan on doing s.t","wordType":"verb"},
// {"french":"reprocher (à qq'un) de fqqc","english":"to reproach (s.o) for doing s.t","wordType":"verb"},
// {"french":"soupçonner (qq'un) de fqqc","english":"to suspect (s.o) of doing s.t","wordType":"verb"},
// {"french":"tâcher de fqqc","english":"to try to do s.t","wordType":"verb"},
// {"french":"s'apercevoir de son erreur","english":"to notice one's mistake","wordType":"verb"},
// {"french":"changer de chaussure","english":"to change into other shoes","wordType":"verb"},
// {"french":"dépendre de qq'un","english":"to depend on s.o","wordType":"verb"},
// {"french":"douter de qq'un","english":"to doubt s.o","wordType":"verb"},
// {"french":"être responsable de qq'un","english":"to be responsible for s.o","wordType":"verb"},
// {"french":"hériter de qq'un","english":"to inherit from s.o","wordType":"verb"},
// {"french":"manquer de temps","english":"to lack time","wordType":"verb"},
// {"french":"se méfier de qq'un","english":"to beware of s.o","wordType":"verb"},
// {"french":"s'occuper de qq'un","english":"to take care of s.o","wordType":"verb"},
// {"french":"parler de qq'un","english":"to talk about s.o","wordType":"verb"},
// {"french":"partir de France","english":"to leave France","wordType":"verb"},
// {"french":"se passer de qq'un","english":"to do without s.o","wordType":"verb"},
// {"french":"Que penses-tu de qq'un?","english":"what is your opinion about s.o?","wordType":"verb"},
// {"french":"profiter de qq'un","english":"to take advantage of s.o","wordType":"verb"},
// {"french":"rêver de qq'un","english":"to dream of s.o","wordType":"verb"},
// {"french":"rire de qq'un","english":"to laugh at s.o","wordType":"verb"},
// {"french":"se souvenir de qq'un","english":"to remember s.o","wordType":"verb"},
// {"french":"un moto","english":"a motorbike","wordType":"noun"},
// {"french":"un panneau","english":"a sign","wordType":"noun"},
// {"french":"un café","english":"a café","wordType":"noun"},
// {"french":"un marché","english":"a market","wordType":"noun"},
// {"french":"feu rouge","english":"red light","wordType":"noun"},
// {"french":"un hôpital","english":"a hospital","wordType":"noun"},
// {"french":"une boite manuelle","english":"a manual gear box","wordType":"noun"},
// {"french":"une assiette","english":"a plate","wordType":"noun"},
// {"french":"une forchette","english":"a fork","wordType":"noun"},
// {"french":"un couvre-lit","english":"a bed cover","wordType":"noun"},
// {"french":"un accélérateur","english":"an accelerator","wordType":"noun"},
// {"french":"conducteur / conductrice","english":"a driver","wordType":"noun"},
// {"french":"un (radio-) réveil","english":"an alarm clock","wordType":"noun"},
// {"french":"une cuillère","english":"a spoon","wordType":"noun"},
// {"french":"un pied","english":"a foot","wordType":"noun"},
// {"french":"un sac poubelle","english":"a rubbish bag","wordType":"noun"},
// {"french":"un parc","english":"a park","wordType":"noun"},
// {"french":"un camion de pompier","english":"a fire engine","wordType":"noun"},
// {"french":"une cadre du lit","english":"a bed frame","wordType":"noun"},
// {"french":"un oreiller (d'un lit)","english":"a pillow","wordType":"noun"},
// {"french":"une bibliothèque","english":"a library","wordType":"noun"},
// {"french":"une banque","english":"a bank","wordType":"noun"},
// {"french":"du vent","english":"the wind","wordType":"noun"},
// {"french":"le soleil","english":"the sun","wordType":"noun"},
// {"french":"une joue","english":"a cheek","wordType":"noun"},
// {"french":"une langue","english":"a tongue","wordType":"noun"},
// {"french":"une cuisine","english":"a kitchen","wordType":"noun"},
// {"french":"une tête","english":"a head","wordType":"noun"},
// {"french":"les gencives","english":"gums","wordType":"noun"},
// {"french":"un four","english":"an oven","wordType":"noun"},
// {"french":"une chaise","english":"a chair","wordType":"noun"},
// {"french":"une fenêtre","english":"a window","wordType":"noun"},
// {"french":"un oreiller (d'une tête)","english":"an ear","wordType":"noun"},
// {"french":"un canapé","english":"a sofa","wordType":"noun"},
// {"french":"une salle de séjour","english":"a living room","wordType":"noun"},
// {"french":"une chambre","english":"a bedroom","wordType":"noun"},
// {"french":"un mur","english":"a wall","wordType":"noun"},
// {"french":"un salon","english":"a lounge","wordType":"noun"},
// {"french":"une entrée","english":"an entrance","wordType":"noun"},
// {"french":"une toilette","english":"a toilet","wordType":"noun"},
// {"french":"les escaliers","english":"the stairs","wordType":"noun"},
// {"french":"un grenier","english":"a loft/attic","wordType":"noun"},
// {"french":"une cave","english":"a cellar","wordType":"noun"},
// {"french":"un sous-sol","english":"a basement","wordType":"noun"},
// {"french":"un couloir","english":"a corridor","wordType":"noun"},
// {"french":"un jardin","english":"a garden","wordType":"noun"},
// {"french":"une pièce","english":"a room","wordType":"noun"},
// {"french":"une jambe","english":"a leg","wordType":"noun"},
// {"french":"une derrière","english":"a bottom","wordType":"noun"},
// {"french":"un abdomen","english":"an abdomen","wordType":"noun"},
// {"french":"un ordinateur (potable)","english":"a computer / laptop","wordType":"noun"},
// {"french":"un main","english":"a hand","wordType":"noun"},
// {"french":"une baignoire","english":"a bathtub","wordType":"noun"},
// {"french":"une fesses","english":"a butt","wordType":"noun"},
// {"french":"un meuble","english":"a piece of furniture","wordType":"noun"},
// {"french":"la neige","english":"snow","wordType":"noun"},
// {"french":"un balcon","english":"a balcony","wordType":"noun"},
// {"french":"un bureau (pièce)","english":"an office","wordType":"noun"},
// {"french":"une moquette / un tapis","english":"a carpet","wordType":"noun"},
// {"french":"une épaule","english":"a shoulder","wordType":"noun"},
// {"french":"un bureau (meuble)","english":"a desk","wordType":"noun"},
// {"french":"un lavabo","english":"a bathroom sink","wordType":"noun"},
// {"french":"une bouche","english":"a mouth","wordType":"noun"},
// {"french":"un bras","english":"an arm","wordType":"noun"},
// {"french":"une dent","english":"a tooth","wordType":"noun"},
// {"french":"une salle de bains","english":"a bathroom","wordType":"noun"},
// {"french":"une arrière-cour","english":"a backyard","wordType":"noun"},
// {"french":"un plafond","english":"a ceiling","wordType":"noun"},
// {"french":"une douche","english":"a shower","wordType":"noun"},
// {"french":"un doigt","english":"a finger","wordType":"noun"},
// {"french":"un oeil / des yeux","english":"an eye / eyes","wordType":"noun"},
// {"french":"une étagère","english":"a shelf","wordType":"noun"},
// {"french":"une taille","english":"a waist","wordType":"noun"},
// {"french":"les cheveux","english":"hair","wordType":"noun"},
// {"french":"un nez","english":"a nose","wordType":"noun"},
// {"french":"un cou","english":"a neck","wordType":"noun"},
// {"french":"une mâchoire","english":"a jaw","wordType":"noun"},
// {"french":"une chiminée","english":"a chimney","wordType":"noun"},
// {"french":"un dos","english":"a back","wordType":"noun"},
// {"french":"une salle à manger","english":"a dining room","wordType":"noun"},
// {"french":"un toit","english":"a roof","wordType":"noun"},
// {"french":"une porche","english":"a porch","wordType":"noun"},
// {"french":"une réfrigérateur","english":"a fridge","wordType":"noun"},
// {"french":"le sol","english":"the ground","wordType":"noun"},
// {"french":"un front","english":"a forehead","wordType":"noun"},
// {"french":"une voiture","english":"a car","wordType":"noun"},
// {"french":"un fouet","english":"a whisk","wordType":"noun"},
// {"french":"une théatre","english":"a theatre","wordType":"noun"},
// {"french":"une quincaillerie","english":"a hardware store","wordType":"noun"},
// {"french":"une fourgonnette","english":"a van","wordType":"noun"},
// {"french":"un médecin","english":"a doctor","wordType":"noun"},
// {"french":"une station service","english":"a service station","wordType":"noun"},
// {"french":"une poissonnerie","english":"a fish mongers","wordType":"noun"},
// {"french":"le polir","english":"the polish","wordType":"noun"},
// {"french":"un balai","english":"a broom","wordType":"noun"},
// {"french":"un plat à four","english":"an oven dish","wordType":"noun"},
// {"french":"un plat de cuisson","english":"a baking dish","wordType":"noun"},
// {"french":"un cinéma","english":"a cinema","wordType":"noun"},
// {"french":"une pharmacie","english":"a pharmacy","wordType":"noun"},
// {"french":"un rond-point","english":"a roundabout","wordType":"noun"},
// {"french":"les pinces","english":"tongs","wordType":"noun"},
// {"french":"une bain-merie","english":"a water cooker","wordType":"noun"},
// {"french":"un camping-car","english":"a motorhome","wordType":"noun"},
// {"french":"un salon de coiffure","english":"a hairdressers","wordType":"noun"},
// {"french":"une caravane","english":"a caravan","wordType":"noun"},
// {"french":"un pneu","english":"a tire","wordType":"noun"},
// {"french":"une roue","english":"a wheel","wordType":"noun"},
// {"french":"une école","english":"a school","wordType":"noun"},
// {"french":"une couverture","english":"a blanket","wordType":"noun"},
// {"french":"une carte grise","english":"a car registration document","wordType":"noun"},
// {"french":"une église","english":"a church","wordType":"noun"},
// {"french":"une pelle","english":"a dustpan","wordType":"noun"},
// {"french":"un club sportif","english":"a sports club","wordType":"noun"},
// {"french":"une temple","english":"a temple","wordType":"noun"},
// {"french":"une éponge","english":"a sponge","wordType":"noun"},
// {"french":"une infirmiere","english":"a nurse","wordType":"noun"},
// {"french":"une mosquée","english":"a mosque","wordType":"noun"},
// {"french":"un volant","english":"a steering wheel","wordType":"noun"},
// {"french":"un pare-brise","english":"a windscreen","wordType":"noun"},
// {"french":"une spatule","english":"a spatula","wordType":"noun"},
// {"french":"une autoroute","english":"a highway","wordType":"noun"},
// {"french":"un bureau de poste","english":"a postoffice","wordType":"noun"},
// {"french":"une kiosque","english":"a kiosk / newstand","wordType":"noun"},
// {"french":"une boulangerie","english":"a bakery","wordType":"noun"},
// {"french":"les rideaux","english":"the curtains","wordType":"noun"},
// {"french":"un mollet","english":"a calf (leg)","wordType":"noun"},
// {"french":"une couvercle","english":"a pan lid","wordType":"noun"},
// {"french":"une commode","english":"a chest of drawers","wordType":"noun"},
// {"french":"un abat-jour","english":"a lampshade","wordType":"noun"},
// {"french":"une sonnette","english":"a bell","wordType":"noun"},
// {"french":"éclair","english":"lightening","wordType":"noun"},
// {"french":"tonnerre","english":"thunder","wordType":"noun"},
// {"french":"un épluceur","english":"a peeler","wordType":"noun"},
// {"french":"un chandail / un pull","english":"a jumper","wordType":"noun"},
// {"french":"des chausson","english":"slippers","wordType":"noun"},
// {"french":"une tempête","english":"a storm","wordType":"noun"},
// {"french":"une cuisse","english":"a thigh","wordType":"noun"},
// {"french":"une chaîne stéréo","english":"a stereo system","wordType":"noun"},
// {"french":"une louche","english":"a ladle","wordType":"noun"},
// {"french":"un servêtement","english":"a tracksuit","wordType":"noun"},
// {"french":"le soleil brille / ensoleillement","english":"sunshine","wordType":"noun"},
// {"french":"un orage","english":"a thunderstorm","wordType":"noun"},
// {"french":"une jointure","english":"a knuckle","wordType":"noun"},
// {"french":"une bross à récurer","english":"a brush / a broom","wordType":"noun"},
// {"french":"un genou","english":"a knee","wordType":"noun"},
// {"french":"un orteil","english":"a toe","wordType":"noun"},
// {"french":"un gilet","english":"a vest / a waistcoat","wordType":"noun"},
// {"french":"un collier","english":"a necklace","wordType":"noun"},
// {"french":"un sein","english":"a breast","wordType":"noun"},
// {"french":"un coude","english":"an elbow","wordType":"noun"},
// {"french":"une lèvre","english":"a lip","wordType":"noun"},
// {"french":"une cocotte","english":"a caserole pot","wordType":"noun"},
// {"french":"un matelas à ressorts","english":"a spring mattress","wordType":"noun"},
// {"french":"un mouchoir","english":"a hankerchief","wordType":"noun"},
// {"french":"une serrure / un verrou","english":"a lock","wordType":"noun"},
// {"french":"un cadenas","english":"a padlock","wordType":"noun"},
// {"french":"une passoire","english":"a strainer","wordType":"noun"},
// {"french":"une minuterie","english":"a timer","wordType":"noun"},
// {"french":"une embouteillage","english":"a traffic jam","wordType":"noun"},
// {"french":"une tourtiere","english":"a pie dish","wordType":"noun"},
// {"french":"un plat","english":"a dish","wordType":"noun"},
// {"french":"un poignet","english":"a wrist","wordType":"noun"},
// {"french":"une veilleuse","english":"a nightlight","wordType":"noun"},
// {"french":"un micro-ondes","english":"a microwave","wordType":"noun"},
// {"french":"une caserne de pompiers","english":"a firestation","wordType":"noun"},
// {"french":"un chiffon","english":"a cloth","wordType":"noun"},
// {"french":"un torchon","english":"a tea towel","wordType":"noun"},
// {"french":"une manique","english":"an oven glove","wordType":"noun"},
// {"french":"de la cire","english":"wax","wordType":"noun"},
// {"french":"une moule à gâteau","english":"a cake tin / mould","wordType":"noun"},
// {"french":"de la pluie","english":"rain","wordType":"noun"},
// {"french":"un commissarial","english":"a police station","wordType":"noun"},
// {"french":"une demangeaison","english":"an itch","wordType":"noun"},
// {"french":"une drap-housse","english":"a mattress cover","wordType":"noun"},
// {"french":"un placard","english":"a cupboard","wordType":"noun"},
// {"french":"une table / plaque de cuisson","english":"cooking hob","wordType":"noun"},
// {"french":"une vitre","english":"a window frame","wordType":"noun"},
// {"french":"une poitrine","english":"a chest","wordType":"noun"},
// {"french":"un gant en caoutchouc","english":"a rubber glove","wordType":"noun"},
// {"french":"une robe de chambre","english":"a dressing gown","wordType":"noun"},
// {"french":"un ongle","english":"a nail (finger/toe)","wordType":"noun"},
// {"french":"une pédale de frein","english":"a brake pedal","wordType":"noun"},
// {"french":"un plumeau","english":"a duster","wordType":"noun"},
// {"french":"une location","english":"a rental","wordType":"noun"},
// {"french":"un nez qui coule","english":"a runny nose","wordType":"noun"},
// {"french":"un panier vapour","english":"a steamer","wordType":"noun"},
// {"french":"une armoire","english":"a wardrobe","wordType":"noun"},
// {"french":"une cheville","english":"an ankle","wordType":"noun"},
// {"french":"un tibia","english":"a shin","wordType":"noun"},
// {"french":"une voie sans issue","english":"a dead end","wordType":"noun"},
// {"french":"un évier","english":"a sink","wordType":"noun"},
// {"french":"un lacet","english":"a shoe lace","wordType":"noun"},
// {"french":"les volets","english":"the shutters","wordType":"noun"},
// {"french":"un ouragan","english":"a hurricane","wordType":"noun"},
// {"french":"une véranda","english":"a patio","wordType":"noun"},
// {"french":"un débardeur","english":"a tanktop","wordType":"noun"},
// {"french":"un cuisinier","english":"a cooker","wordType":"noun"},
// {"french":"degrêle","english":"hail","wordType":"noun"},
// {"french":"une salopette","english":"overalls","wordType":"noun"},
// {"french":"une impasse","english":"a dead end / impass","wordType":"noun"},
// {"french":"une couette","english":"a quilt / duvet","wordType":"noun"},
// {"french":"une hanche","english":"a hip","wordType":"noun"},
// {"french":"du brouillard","english":"fog","wordType":"noun"},
// {"french":"loisirs / passe-temps","english":"hobbies","wordType":"noun"},
// {"french":"un sac à main","english":"a handbag / purse","wordType":"noun"},
// {"french":"une jupe","english":"a skirt","wordType":"noun"},
// {"french":"un sweat-shirt","english":"a sweatshirt","wordType":"noun"},
// {"french":"un uniforme","english":"a uniform","wordType":"noun"},
// {"french":"un bracelet","english":"a bracelet","wordType":"noun"},
// {"french":"une ceinture","english":"a belt","wordType":"noun"},
// {"french":"une portefeuille","english":"a wallet","wordType":"noun"},
// {"french":"une robe","english":"a dress","wordType":"noun"},
// {"french":"une chemisier","english":"a blouse","wordType":"noun"},
// {"french":"un short","english":"a pair of shorts","wordType":"noun"},
// {"french":"un smoking","english":"a tuxedo","wordType":"noun"},
// {"french":"un costume","english":"a suit","wordType":"noun"},
// {"french":"un plantalon","english":"a pair of trousers","wordType":"noun"},
// {"french":"des bijoux","english":"jewelry","wordType":"noun"},
// {"french":"les bottes","english":"boots","wordType":"noun"},
// {"french":"les chaussures","english":"shoes","wordType":"noun"},
// {"french":"une cravate","english":"a tie","wordType":"noun"},
// {"french":"un hôtel de ville","english":"a city hall","wordType":"noun"},
// {"french":"une boucherie","english":"a butchers","wordType":"noun"},
// {"french":"une poêle","english":"a frying pan","wordType":"noun"},
// {"french":"une casserole","english":"a pan","wordType":"noun"},
// {"french":"une marmite","english":"a cooking pot","wordType":"noun"},
// {"french":"un ambulance","english":"an ambulance","wordType":"noun"},
// {"french":"sans interdit","english":"one way / no entry","wordType":"noun"},
// {"french":"une râpe à fromage","english":"a cheese grater","wordType":"noun"},
// {"french":"la gazole","english":"the deisel","wordType":"noun"},
// {"french":"un bol à mixer","english":"a mixing bowl","wordType":"noun"},
// {"french":"une tête de lit","english":"a bedhead","wordType":"noun"},
// {"french":"un presse-ail","english":"a garlic press","wordType":"noun"},
// {"french":"une pris de courant","english":"a plug socket / outlet","wordType":"noun"},
// {"french":"un tiroir","english":"a drawer","wordType":"noun"},
// {"french":"un couteau","english":"a knife","wordType":"noun"},
// {"french":"une lampe","english":"a lamp","wordType":"noun"},
// {"french":"une ouvre-boite","english":"a can / tin opener","wordType":"noun"},
// {"french":"un permis de conduite","english":"a driving license","wordType":"noun"},
// {"french":"une péage","english":"a toll-booth","wordType":"noun"},
// {"french":"une table de nuit","english":"bedside table / night stand","wordType":"noun"},
// {"french":"les stores de fenêtre","english":"the window blinds","wordType":"noun"},
// {"french":"un aspirateur","english":"a hoover","wordType":"noun"},
// {"french":"un matelas","english":"a mattress","wordType":"noun"},
// {"french":"un pharmacien","english":"a pharmacist","wordType":"noun"},
// {"french":"un magasin de meubles","english":"a furniture store","wordType":"noun"},
// {"french":"une librairie","english":"a book store","wordType":"noun"},
// {"french":"un tabac","english":"a tobacconist","wordType":"noun"},
// {"french":"une synagogue","english":"a synagogue","wordType":"noun"},
// {"french":"un seau","english":"a bucket","wordType":"noun"},
// {"french":"une épicerie","english":"a green grocers","wordType":"noun"},
// {"french":"un camion","english":"a lorry","wordType":"noun"},
// {"french":"reasonable","english":"sensible / reasonable","wordType":"adj"},
// {"french":"sensible","english":"sinsitive","wordType":"adj"},
// {"french":"orageux","english":"stormy","wordType":"adj"},
// {"french":"d'abord","english":"first / to start","wordType":"adj"},
// {"french":"environ","english":"about / around","wordType":"adj"},
// {"french":"par là","english":"through there","wordType":"adj"},
// {"french":"quant à","english":"as for","wordType":"adj"},
// {"french":"blessé","english":"hurt","wordType":"adj"},
// {"french":"actuellement","english":"curently","wordType":"adj"},
// {"french":"en fait / en realité","english":"actually / in fact","wordType":"adj"},
// {"french":"être allergique (aux noix)","english":"to be allergic (to nuts)","wordType":"adj"},
// {"french":"(con)gelé / glacé","english":"frozen","wordType":"adj"},
// {"french":"être fatigué","english":"to be tired","wordType":"adj"},
// {"french":"pénible","english":"annoying","wordType":"adj"},
// {"french":"tout droit","english":"straight ahead","wordType":"adj"},
// {"french":"nuageux","english":"cloudy","wordType":"adj"},
// {"french":"frais","english":"fresh","wordType":"adj"},
// {"french":"chez ___","english":"the house of ___","wordType":"adj"},
// {"french":"là-haut","english":"up there","wordType":"adj"},
// {"french":"en bas","english":"down there","wordType":"adj"},
// {"french":"près de","english":"near to","wordType":"adj"},
// {"french":"en face de","english":"in front of","wordType":"adj"},
// {"french":"selon","english":"according to","wordType":"adj"},
// {"french":"avant","english":"before","wordType":"adj"},
// {"french":"depuis","english":"since","wordType":"adj"},
// {"french":"entre","english":"between","wordType":"adj"},
// {"french":"parmi","english":"among","wordType":"adj"},
// {"french":"contre","english":"against","wordType":"adj"},
// {"french":"à côté de","english":"next to","wordType":"adj"},
// {"french":"(in)poli","english":"(in)polite","wordType":"adj"},
// {"french":"effrayé","english":"afraid","wordType":"adj"},
// {"french":"fou / folle","english":"crazy","wordType":"adj"},
// {"french":"solitaire","english":"lonely","wordType":"adj"},
// {"french":"pressé","english":"pressed / hurried / rushed","wordType":"adj"},
// {"french":"lâche","english":"coward","wordType":"adj"},
// {"french":"(in)juste","english":"(un)fair","wordType":"adj"},
// {"french":"sans préjugés","english":"open-minded / without prejudice","wordType":"adj"},
// {"french":"similaire / semblable à","english":"similar","wordType":"adj"},
// {"french":"moche / laid","english":"ugly","wordType":"adj"},
// {"french":"(mal)honnête","english":"(dis)honest","wordType":"adj"},
// {"french":"devant","english":"in front of","wordType":"adj"},
// {"french":"justque","english":"until","wordType":"adj"},
// {"french":"presque","english":"almost","wordType":"adj"},
// {"french":"après","english":"after","wordType":"adj"},
// {"french":"hors de","english":"outside of","wordType":"adj"},
// {"french":"là bas","english":"down there","wordType":"adj"},
// {"french":"vers","english":"towards","wordType":"adj"},
// {"french":"humide","english":"wet / humid","wordType":"adj"},
// {"french":"suivant","english":"following","wordType":"adj"},
// {"french":"souvent","english":"often","wordType":"adj"},
// {"french":"derrière","english":"behind","wordType":"adj"},
// {"french":"loin de","english":"far from","wordType":"adj"},
// {"french":"malgré","english":"despite","wordType":"adj"},
// {"french":"dès que","english":"as soon as","wordType":"adj"},
// {"french":"dès","english":"from (a start pos)","wordType":"adj"},
// {"french":"pendant","english":"while","wordType":"adj"},
// {"french":"amusant","english":"fun","wordType":"adj"},
// {"french":"fâché","english":"angry","wordType":"adj"},
// {"french":"amical","english":"friendly","wordType":"adj"},
// {"french":"épuisé","english":"exhausted","wordType":"adj"},
// {"french":"fort","english":"strong","wordType":"adj"},
// {"french":"lourd","english":"heavy","wordType":"adj"},
// {"french":"froid","english":"cold","wordType":"adj"},
// {"french":"ennuyeux","english":"boring","wordType":"adj"},
// {"french":"drôle / marrant","english":"funny","wordType":"adj"},
// {"french":"patriotique","english":"patriotic","wordType":"adj"},
// {"french":"biizarre","english":"strange","wordType":"adj"},
// {"french":"vieux / vieille","english":"old","wordType":"adj"},
// {"french":"beau / belle","english":"handsome/ beautiful","wordType":"adj"},
// {"french":"ravi","english":"delighted","wordType":"adj"},
// {"french":"triste","english":"sad","wordType":"adj"},
// {"french":"courageux","english":"courageuos","wordType":"adj"},
// {"french":"confus","english":"confused","wordType":"adj"},
// {"french":"content","english":"happy","wordType":"adj"},
// {"french":"pauvre","english":"poor","wordType":"adj"},
// {"french":"sérieux","english":"serious","wordType":"adj"},
// {"french":"tranquille","english":"quiet","wordType":"adj"},
// {"french":"petit","english":"small","wordType":"adj"},
// {"french":"timide","english":"small","wordType":"adj"},
// {"french":"mignon","english":"cute","wordType":"adj"},
// {"french":"grand","english":"big","wordType":"adj"},
// {"french":"gros","english":"fat","wordType":"adj"},
// {"french":"paresseux","english":"lazy","wordType":"adj"},
// {"french":"imaginatif","english":"imaginative","wordType":"adj"},
// {"french":"raffiné","english":"refined","wordType":"adj"},
// {"french":"travailleur","english":"worker","wordType":"adj"},
// {"french":"impulsif","english":"impulsive","wordType":"adj"},
// {"french":"léger","english":"light (weight)","wordType":"adj"},
// {"french":"(in)actif","english":"(in)active","wordType":"adj"},
// {"french":"jeune","english":"young","wordType":"adj"},
// {"french":"faible","english":"weak","wordType":"adj"},
// {"french":"intéressant","english":"interesting","wordType":"adj"},
// {"french":"doux","english":"soft","wordType":"adj"},
// {"french":"joli","english":"pretty","wordType":"adj"},
// {"french":"plein","english":"full","wordType":"adj"},
// {"french":"pareil","english":"the same","wordType":"adj"},
// {"french":"gentil","english":"kind / nice","wordType":"adj"},
// {"french":"(mal)heureux","english":"(un)happy","wordType":"adj"},
// {"french":"intelligent","english":"intelligent","wordType":"adj"},
// {"french":"curieux","english":"curious","wordType":"adj"},
// {"french":"ambitieux","english":"ambitious","wordType":"adj"},
// {"french":"organisé","english":"organised","wordType":"adj"},
// {"french":"efficace","english":"effective / efficient","wordType":"adj"},
// {"french":"mince","english":"thin","wordType":"adj"},
// {"french":"meilleur","english":"better","wordType":"adj"},
// {"french":"égoïste","english":"selfish","wordType":"adj"},
// {"french":"ouvert","english":"open","wordType":"adj"},
// {"french":"naïf","english":"naïve","wordType":"adj"},
// {"french":"méchant","english":"mean","wordType":"adj"},
// {"french":"malin","english":"malignant","wordType":"adj"},
// {"french":"âgé","english":"old","wordType":"adj"},
// {"french":"sportif","english":"sporty","wordType":"adj"},
// {"french":"snob","english":"snobish","wordType":"adj"},
// {"french":"stupide","english":"stupid","wordType":"adj"},
// {"french":"inquiet","english":"worried","wordType":"adj"},
// {"french":"haut","english":"high","wordType":"adj"},
// {"french":"bas","english":"low","wordType":"adj"},
// {"french":"sympa","english":"nice","wordType":"adj"},
// {"french":"être malade","english":"to be sick","wordType":"adj"},
// {"french":"être diabétique","english":"to be diabetic","wordType":"adj"},
// {"french":"avoir le rhume des foins","english":"to have hayfever","wordType":"verb"},
// {"french":"avoir le mal des transports","english":"to have travel sickness","wordType":"verb"},
// {"french":"avoir une sinusute","english":"to have a sinus infection (sinusitis)","wordType":"verb"},
// {"french":"avoir des brûlures d'estomac","english":"to have heartburn","wordType":"verb"},
// {"french":"avoir la grippe","english":"to have the flu","wordType":"verb"},
// {"french":"avoir mal aux dents","english":"to have a toothache","wordType":"verb"},
// {"french":"avoir mal à l'estomac","english":"to have a stomach ache","wordType":"verb"},
// {"french":"avoir un rhume / être enrhumé","english":"to have a cold","wordType":"verb"},
// {"french":"avoir de la fièvre","english":"to have a fever","wordType":"verb"},
// {"french":"avoir mal de mer","english":"to be / have seasickness","wordType":"verb"},
// {"french":"avoir mal à la tête","english":"to have a headache","wordType":"verb"},
// {"french":"avoir de l'arthrite","english":"to have arthritus","wordType":"verb"},
// {"french":"avoire la gueule de bois","english":"to have a hangover","wordType":"verb"},
// {"french":"saigner du nez","english":"to have a nosebleed","wordType":"verb"},
// {"french":"essuyer","english":"to wipe","wordType":"verb"},
// {"french":"éternuer","english":"to sneeze","wordType":"verb"},
// {"french":"céder le passage","english":"to give way","wordType":"verb"},
// {"french":"frotter","english":"to rub / scrub","wordType":"verb"},
// {"french":"faire le plein","english":"to refuel","wordType":"verb"},
// {"french":"passer (un examen)","english":"to take (an exam)","wordType":"verb"},
// {"french":"tousser","english":"to cough","wordType":"verb"},
// {"french":"stationner","english":"to park","wordType":"verb"},
// {"french":"saigner","english":"to bleed","wordType":"verb"},
// {"french":"vomir","english":"to vomit","wordType":"verb"},
// {"french":"faire le lit","english":"to make the bed","wordType":"verb"},
// {"french":"doubler","english":"to overtake","wordType":"verb"},
// {"french":"sortir les poubelles","english":"to take out the rubbish","wordType":"verb"},
// {"french":"sécher","english":"to dry","wordType":"verb"},
// {"french":"recycler","english":"to recycle","wordType":"verb"},
// {"french":"balayer","english":"to sweep","wordType":"verb"},
// {"french":"rouler","english":"to roll","wordType":"verb"},
// {"french":"tourner","english":"to turn","wordType":"verb"},
// {"french":"vider","english":"to empty","wordType":"verb"},
// {"french":"traverser","english":"to cross","wordType":"verb"},
// {"french":"ranger","english":"to tidy","wordType":"verb"},
// {"french":"nettoyer","english":"to clean","wordType":"verb"}
// ];
